{
  "hash": "4d1ac03874a1b6e40efe2303513777b2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Datenbericht\"\n---\n\n# Datenbericht\n\nDer Datenbericht dokumentiert alle im Projekt verwendeten Daten, von der Rohdatenbeschaffung bis hin zu den drei abgeleiteten Analyse-Datensätzen. Ziel ist die Nachvollziehbarkeit der Befunde und die Möglichkeit, den vollen Datenfluss von Dritten reproduzieren zu lassen.\n\n\n\n## Rohdaten\n\n### Übersicht der Rohdatensätze\n\nWir beziehen die Daten vom öffentlichen Export der OpenParlData-Plattform [@openparldata]. Die Plattform bietet eine API, wir nutzen jedoch direkt die Quelldateien unter [files.openparldata.ch/exports/](https://files.openparldata.ch/exports/), die wöchentlich als gzippte NDJSON-Dateien aktualisiert werden. Für unsere Fragestellung (Alter, Eintritt und Amtsdauer von Bundespolitiker:innen) reichen zwei der rund 15 verfügbaren Exports.\n\n| Name | Quelle | Speicherort |\n|---|---|---|\n| `persons.ndjson` | OpenParlData Export: Personeneinträge inkl. Biografie, Partei, Wahlkreis. | `data/raw/persons.ndjson` (entpackt), bezogen von `https://files.openparldata.ch/exports/persons.ndjson.gz` |\n| `memberships.ndjson` | OpenParlData Export: Mitgliedschaften in Gremien (Räte, Kommissionen, Fraktionen, Parteien). | `data/raw/memberships.ndjson` (entpackt), bezogen von `https://files.openparldata.ch/exports/memberships.ndjson.gz` |\n\n: Übersicht der verwendeten Rohdatensätze. {#tbl-raw-overview}\n\nDas Beschaffungs-Skript `eda/1_gather_data.py` lädt beide Dateien herunter, entpackt sie und konvertiert sie nach Parquet. Bereits vorhandene Dateien werden nicht erneut heruntergeladen.\n\n```python\n# eda/1_gather_data.py (Auszug)\nOPENPARL_BASE = \"https://files.openparldata.ch/exports\"\nFILES = [\"persons\", \"memberships\"]\n\ndef ensure_ndjson(name: str) -> Path:\n    ndjson_path = RAW_DIR / f\"{name}.ndjson\"\n    gz_path = RAW_DIR / f\"{name}.ndjson.gz\"\n    if ndjson_path.exists():\n        return ndjson_path\n    if not gz_path.exists():\n        urllib.request.urlretrieve(f\"{OPENPARL_BASE}/{name}.ndjson.gz\", gz_path)\n    with gzip.open(gz_path, \"rb\") as f_in, open(ndjson_path, \"wb\") as f_out:\n        shutil.copyfileobj(f_in, f_out)\n    return ndjson_path\n```\n\n**Rechtliches und Governance.** OpenParlData ist eine öffentliche Initiative ohne formelle Lizenzangabe; die zugrundeliegenden Daten stammen aus den offiziellen Biografien der parlament.ch Webseite und sind als öffentlich zugängliche Verwaltungsdaten zu verstehen. Die Daten sind somit als \"öffentlich\" einzuordnen.\n\n### Details `persons.ndjson`\n\nDer Personen-Export enthält biografische Stammdaten zu allen je erfassten Mandatsträger:innen auf Bundes- und Kantonsebene: Name, Geburtsdatum, Geschlecht, Partei, Wahlkreis, parlamentarischer Sektor (Nationalrat oder Ständerat), aktuelle Aktivität sowie eine Vielzahl von Querverweisen auf externe IDs (Wikidata, parlament.ch). Wir filtern für unsere Analyse auf `body_key == \"CHE\"`, also auf die Bundesebene.\n\n#### Datenkatalog\n\nDer vollständige Katalog mit allen 60 Spalten liegt unter `eda/output/catalogue_persons_clean_CHE.csv`. Hier sind die für die Altersanalyse relevanten Spalten:\n\n::: {#tbl-cat-persons .cell tbl-cap='Datenkatalog persons.ndjson (Auszug der projektrelevanten Spalten).' execution_count=2}\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Index</th>\n      <th>Spalte</th>\n      <th>Datentyp</th>\n      <th>Fehlend (%)</th>\n      <th>Unique</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>id</td>\n      <td>int64</td>\n      <td>0.0</td>\n      <td>3916</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>body_key</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>fullname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>3868</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>firstname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1441</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>lastname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2470</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>6</td>\n      <td>birthday</td>\n      <td>datetime64[ms]</td>\n      <td>6.7</td>\n      <td>3542</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>gender</td>\n      <td>object</td>\n      <td>6.6</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>party_de</td>\n      <td>object</td>\n      <td>7.4</td>\n      <td>77</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>party_harmonized_de</td>\n      <td>object</td>\n      <td>18.5</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>10</td>\n      <td>electoral_district_de</td>\n      <td>object</td>\n      <td>7.0</td>\n      <td>74</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11</td>\n      <td>parliament_sector</td>\n      <td>object</td>\n      <td>93.7</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>12</td>\n      <td>active</td>\n      <td>object</td>\n      <td>0.4</td>\n      <td>2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Datencharakteristik und Qualität\n\nDie zentrale Variable für unsere Analyse ist `birthday`. Auf Bundesebene ist die Abdeckung exzellent:\n\n::: {#persons-coverage .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\nCHE-Personen total: 3,916\nDavon mit Geburtsdatum: 3,655 (93.3 %)\nIm plausiblen Bereich (1800–2015): 3,576\nFrühester Geburtstag: 1800-01-18\nSpätester Geburtstag: 1996-12-26\n```\n:::\n:::\n\n\n::: {#cell-fig-birthday-by-decade .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Anzahl CHE-Personen mit erfasstem Geburtsdatum je Geburtsjahrzent. Die Abdeckung ist über alle Jahrzente hoch.](data_report_files/figure-html/fig-birthday-by-decade-output-1.png){#fig-birthday-by-decade width=938 height=397}\n:::\n:::\n\n\nDie Geschlechtsangabe ist ebenfalls flächendeckend erfasst:\n\n::: {#cell-persons-gender .cell execution_count=5}\n\n::: {#persons-gender .cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Geschlecht</th>\n      <th>Anzahl</th>\n      <th>Anteil (%)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>m</td>\n      <td>3352</td>\n      <td>85.6</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>f</td>\n      <td>307</td>\n      <td>7.8</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>(fehlend)</td>\n      <td>257</td>\n      <td>6.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nBei der Parteizugehörigkeit fällt auf, dass viele Parteinamen über die Zeit gewandert sind (CVP, Mitte, FDP-Liberale usw.). OpenParlData stellt unter `party_harmonized_de` bereits konsolidierte Bezeichnungen bereit; wir nutzen sie für historische Vergleiche.\n\n::: {#tbl-party-top .cell tbl-cap='Häufigste harmonisierte Parteibezeichnungen (Top 10).' execution_count=6}\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Anzahl</th>\n    </tr>\n    <tr>\n      <th>party_harmonized_de</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>FDP.Die Liberalen</th>\n      <td>1211</td>\n    </tr>\n    <tr>\n      <th>Christlichdemokratische Volkspartei der Schweiz</th>\n      <td>732</td>\n    </tr>\n    <tr>\n      <th>None</th>\n      <td>723</td>\n    </tr>\n    <tr>\n      <th>Sozialdemokratische Partei</th>\n      <td>493</td>\n    </tr>\n    <tr>\n      <th>Schweizerische Volkspartei</th>\n      <td>335</td>\n    </tr>\n    <tr>\n      <th>Liberal-Demokratische Partei</th>\n      <td>108</td>\n    </tr>\n    <tr>\n      <th>Die Grünen</th>\n      <td>65</td>\n    </tr>\n    <tr>\n      <th>Landesring der Unabhängigen</th>\n      <td>62</td>\n    </tr>\n    <tr>\n      <th>Die Mitte</th>\n      <td>53</td>\n    </tr>\n    <tr>\n      <th>Grünliberale Partei</th>\n      <td>26</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Details `memberships.ndjson`\n\nDer Mitgliedschafts-Export enthält pro Person eine Zeile pro Gremium, in dem die Person sass oder noch sitzt: Nationalrat, Ständerat, Kommissionen, Fraktionen, Interessengruppen, Parteien. Jede Mitgliedschaft hat ein Anfangs- und Enddatum (`begin_date`, `end_date`), einen Typ (`type_harmonized_de`) und einen Gruppennamen (`group_name_de`). Diese Doppelung erlaubt es uns, die Parlamentssitze (Typ `Parlament (Legislativrat)` mit Gruppe `Nationalrat` oder `Ständerat`) sauber zu isolieren.\n\n#### Datenkatalog\n\nVollständiger Katalog: `eda/output/catalogue_memberships_clean_CHE.csv`. Relevant für unsere Analyse:\n\n::: {#tbl-cat-memberships .cell tbl-cap='Datenkatalog memberships.ndjson (Auszug der projektrelevanten Spalten).' execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Index</th>\n      <th>Spalte</th>\n      <th>Datentyp</th>\n      <th>Fehlend (%)</th>\n      <th>Unique</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>id</td>\n      <td>int64</td>\n      <td>0.0</td>\n      <td>22122</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>body_key</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>person_id</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>3708</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>group_name_de</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>445</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>role_name_de</td>\n      <td>object</td>\n      <td>27.1</td>\n      <td>15</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>6</td>\n      <td>begin_date</td>\n      <td>datetime64[ms]</td>\n      <td>24.3</td>\n      <td>1544</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>end_date</td>\n      <td>datetime64[ms]</td>\n      <td>29.9</td>\n      <td>2044</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>active</td>\n      <td>object</td>\n      <td>2.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>type_harmonized_de</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>9</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Datencharakteristik und Qualität\n\nAuf Bundesebene existieren rund 22'000 Mitgliedschaftseinträge. Die Mehrheit entfällt auf Kommissionen und Interessengruppen; für unsere Frage interessieren ausschliesslich die Mitgliedschaften vom Typ `Parlament (Legislativrat)`:\n\n::: {#cell-fig-membership-types .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Verteilung der CHE-Mitgliedschaften nach Typ. Für die Altersanalyse verwenden wir ausschliesslich den Typ 'Parlament (Legislativrat)'.](data_report_files/figure-html/fig-membership-types-output-1.png){#fig-membership-types width=939 height=458}\n:::\n:::\n\n\nInnerhalb des Typs `Parlament (Legislativrat)` ergibt sich eine klare Zweiteilung in Nationalrat und Ständerat:\n\n::: {#tbl-parl-groups .cell tbl-cap='Aufteilung der Parlamentsmitgliedschaften auf die beiden Kammern.' execution_count=9}\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Anzahl</th>\n    </tr>\n    <tr>\n      <th>group_name_de</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Nationalrat</th>\n      <td>4398</td>\n    </tr>\n    <tr>\n      <th>Ständerat</th>\n      <td>1219</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nDas Beobachtungsfenster reicht bis 1848 zurück:\n\n::: {#memb-date-range .cell execution_count=10}\n\n::: {.cell-output .cell-output-stdout}\n```\nFrühestes begin_date: 1848-11-06\nSpätestes begin_date: 2026-06-01\nAnteil ohne end_date (laufende Mandate): 4.4 %\n```\n:::\n:::\n\n\n## Verarbeitete Daten\n\nAus den beiden Rohdatensätzen erzeugt `eda/2_etl_politicians.py` drei kompakte Analyse-Tabellen. Die Verarbeitungsschritte sind:\n\n1. **Bundesebene isolieren** (`body_key == \"CHE\"`).\n2. **Geburtstage validieren** (Geburtsjahr zwischen 1800 und 2015).\n3. **Parlamentssitze isolieren** (`type_harmonized_de == \"Parlament (Legislativrat)\"` und Gruppe Nationalrat oder Ständerat).\n4. **Join** Mitgliedschaften × Personen via `person_id`.\n5. **Anreichern** pro Mitgliedschaft mit `entry_age`, `exit_age`, `duration_years`.\n\n```python\n# eda/2_etl_politicians.py (Auszug)\nparl[\"entry_age\"] = ((parl[\"begin_date\"] - parl[\"birthday\"]).dt.days / 365.25).round(2)\nparl[\"exit_age\"]  = ((parl[\"end_date_eff\"] - parl[\"birthday\"]).dt.days / 365.25).round(2)\nparl[\"duration_years\"] = ((parl[\"end_date_eff\"] - parl[\"begin_date\"]).dt.days / 365.25).round(2)\n```\n\nFür laufende Mandate (kein `end_date`) verwenden wir das heutige Datum als provisorisches Ende; die betroffenen Zeilen werden über `is_active = True` markiert, sodass nachgelagerte Auswertungen sie bei Bedarf ausschliessen können.\n\n### Übersicht der verarbeiteten Datensätze\n\n| Name | Beschreibung | Speicherort |\n|---|---|---|\n| `politicians.parquet` | Eine Zeile pro Bundespolitiker:in mit aggregierten Karriere-Kennzahlen. | `data/processed/politicians.parquet` |\n| `parliament_memberships.parquet` | Eine Zeile pro NR- oder SR-Mitgliedschaft mit Alters- und Dauer-Berechnungen. | `data/processed/parliament_memberships.parquet` |\n| `parliament_yearly.parquet` | Jahres-Snapshot per 1. Juli: wer war im Parlament, wie alt? | `data/processed/parliament_yearly.parquet` |\n\n: Übersicht der drei verarbeiteten Datensätze. {#tbl-processed-overview}\n\n### Details `politicians.parquet`\n\nEine Zeile pro Person, die mindestens einmal in Nationalrat oder Ständerat sass und ein erfasstes Geburtsdatum hat.\n\n::: {#tbl-cat-politicians .cell tbl-cap='Datenkatalog politicians.parquet.' execution_count=11}\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Index</th>\n      <th>Spalte</th>\n      <th>Datentyp</th>\n      <th>Fehlend (%)</th>\n      <th>Unique</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>person_id</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>3546</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>firstname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1307</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>lastname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2256</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>birthday</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>3437</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>gender</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>6</td>\n      <td>party_de</td>\n      <td>object</td>\n      <td>0.5</td>\n      <td>77</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>party_harmonized_de</td>\n      <td>object</td>\n      <td>11.8</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>canton</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>74</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>first_entry_date</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>680</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>10</td>\n      <td>last_seat_end</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>1146</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11</td>\n      <td>entry_age</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>2156</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>12</td>\n      <td>total_tenure_years</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>1365</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>13</td>\n      <td>num_memberships</td>\n      <td>int64</td>\n      <td>0.0</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>14</td>\n      <td>chambers</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>15</td>\n      <td>currently_active</td>\n      <td>bool</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>16</td>\n      <td>age_today</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>1572</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-politicians-summary .cell execution_count=12}\n\n::: {.cell-output .cell-output-stdout}\n```\nAnzahl Bundespolitiker:innen in der Analyse: 3,546\nDavon aktuell im Amt: 237\n\nUnivariate Statistiken (Jahre):\n```\n:::\n\n::: {#politicians-summary .cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>entry_age</th>\n      <th>total_tenure_years</th>\n      <th>age_today</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>3546.0</td>\n      <td>3546.0</td>\n      <td>3546.0</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>46.3</td>\n      <td>10.7</td>\n      <td>134.7</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>8.7</td>\n      <td>7.8</td>\n      <td>51.6</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>21.3</td>\n      <td>-0.0</td>\n      <td>29.4</td>\n    </tr>\n    <tr>\n      <th>10%</th>\n      <td>34.9</td>\n      <td>2.4</td>\n      <td>67.4</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>46.3</td>\n      <td>9.0</td>\n      <td>133.7</td>\n    </tr>\n    <tr>\n      <th>90%</th>\n      <td>57.7</td>\n      <td>21.0</td>\n      <td>207.2</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>81.4</td>\n      <td>48.5</td>\n      <td>226.3</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-entry-age .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Verteilung des Eintrittsalters über alle 3'546 Bundespolitiker:innen (1850–2025).](data_report_files/figure-html/fig-entry-age-output-1.png){#fig-entry-age width=939 height=398}\n:::\n:::\n\n\n::: {#cell-fig-entry-vs-tenure .cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![Eintrittsalter gegen Gesamt-Mandatsdauer. Wer früh einsteigt, kann länger bleiben; die schwache negative Korrelation ist sichtbar.](data_report_files/figure-html/fig-entry-vs-tenure-output-1.png){#fig-entry-vs-tenure width=939 height=457}\n:::\n:::\n\n\n### Details `parliament_memberships.parquet`\n\nEine Zeile pro einzelne Mitgliedschaft im Nationalrat oder Ständerat.\n\n::: {#tbl-cat-pmem .cell tbl-cap='Datenkatalog parliament_memberships.parquet.' execution_count=15}\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Index</th>\n      <th>Spalte</th>\n      <th>Datentyp</th>\n      <th>Fehlend (%)</th>\n      <th>Unique</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>person_id</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>3546</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>firstname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1307</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>lastname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2256</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>birthday</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>3437</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>gender</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>6</td>\n      <td>party_de</td>\n      <td>object</td>\n      <td>0.4</td>\n      <td>77</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>party_harmonized_de</td>\n      <td>object</td>\n      <td>10.1</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>electoral_district_de</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>74</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>chamber</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>10</td>\n      <td>begin_date</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>757</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11</td>\n      <td>end_date</td>\n      <td>datetime64[ms]</td>\n      <td>4.4</td>\n      <td>1279</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>12</td>\n      <td>end_date_eff</td>\n      <td>datetime64[ms]</td>\n      <td>0.0</td>\n      <td>1280</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>13</td>\n      <td>entry_age</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>2776</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>14</td>\n      <td>exit_age</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>2892</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>15</td>\n      <td>duration_years</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>1140</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>16</td>\n      <td>is_active</td>\n      <td>bool</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-duration-by-chamber .cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![Verteilung der Mandatsdauer pro Kammer, nur abgeschlossene Mandate. Der Ständerat zeigt längere Mandate (Median sechs Jahre versus vier im Nationalrat) bei stärkerer Streuung.](data_report_files/figure-html/fig-duration-by-chamber-output-1.png){#fig-duration-by-chamber width=940 height=398}\n:::\n:::\n\n\n### Details `parliament_yearly.parquet`\n\nJahres-Snapshot: für jedes Jahr von 1850 bis 2025 eine Zeile pro Person, die am 1. Juli dieses Jahres in NR oder SR sass, plus ihr Alter zu jenem Stichtag. Dieser Datensatz ist Kernstück der Haupt-Visualisierung.\n\n::: {#tbl-cat-yearly .cell tbl-cap='Datenkatalog parliament_yearly.parquet.' execution_count=17}\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Index</th>\n      <th>Spalte</th>\n      <th>Datentyp</th>\n      <th>Fehlend (%)</th>\n      <th>Unique</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>person_id</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>3478</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>firstname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>1274</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>lastname</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2224</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>chamber</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>gender</td>\n      <td>object</td>\n      <td>0.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>6</td>\n      <td>party_de</td>\n      <td>object</td>\n      <td>0.5</td>\n      <td>76</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>party_harmonized_de</td>\n      <td>object</td>\n      <td>9.8</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>age</td>\n      <td>float64</td>\n      <td>0.0</td>\n      <td>4559</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>year</td>\n      <td>int64</td>\n      <td>0.0</td>\n      <td>176</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-yearly-headcount .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![Anzahl Parlamentsmitglieder pro Jahr und Kammer. Der Nationalrat wuchs in mehreren Etappen auf die heutigen 200 Sitze; der Ständerat hält bei 46.](data_report_files/figure-html/fig-yearly-headcount-output-1.png){#fig-yearly-headcount width=939 height=398}\n:::\n:::\n\n\n::: {#cell-fig-median-age .cell execution_count=19}\n\n::: {.cell-output .cell-output-display}\n![Median-Alter pro Kammer über die Zeit. Das ist die Headline-Grafik der Analyse und beantwortet die Forschungsfrage direkt.](data_report_files/figure-html/fig-median-age-output-1.png){#fig-median-age width=939 height=398}\n:::\n:::\n\n\n## Schlüsselbefunde\n\n| Befund | Quelle |\n|---|---|\n| Median-Alter NR in den 2020ern: 51.6 Jahre, so jung wie seit 100 Jahren nicht mehr. | `parliament_yearly` Median pro Jahrzent |\n| Median-Alter SR liegt aktuell bei rund 60 Jahren und ist konstant höher als NR. | `parliament_yearly` Median pro Jahrzent |\n| Höhepunkt der Alterung war nicht heute, sondern in den 1950ern (NR 56, SR 61). | `parliament_yearly` Median pro Jahrzent |\n| Eintrittsalter ist seit 1880 stabil bei 46 bis 49 Jahren. | `politicians.entry_age` Median pro Eintrittsjahrzent |\n\n## Datenqualität und Limitierungen\n\n- **Geburtstagslücke:** Rund 7 % der Bundespolitiker:innen haben kein erfasstes Geburtsdatum. Die Lücke konzentriert sich auf historische Datensätze. Für moderne Mandate ist die Abdeckung praktisch vollständig.\n- **Aktive Mandate:** Für laufende Mandate ist `end_date` leer; für Berechnungen wird das heutige Datum als provisorisches Ende verwendet.\n- **Parteibezeichnungen:** Parteinamen ändern sich (CVP zu Die Mitte, FDP zu FDP-Liberale). Wir nutzen die harmonisierten Bezeichnungen `party_harmonized_de`.\n- **Stichtag des Snapshots:** Wir messen die Altersverteilung jeweils am 1. Juli. Mandate, die zwischen Januar und Juli beginnen oder enden, sind in dem jeweiligen Jahr je nach Datum enthalten oder nicht.\n\n## Reproduzierbarkeit\n\n```bash\nuv sync\nuv run python eda/1_gather_data.py     # Download + NDJSON zu Parquet\nuv run python eda/2_etl_politicians.py # ETL für die Altersanalyse\nuv run python eda/3_eda.py             # EDA-Dump in eda/output/\nuv run streamlit run deployment/app.py # Interaktives Visualisierungsprodukt\n```\n\nDie vollständigen EDA-Outputs befinden sich im Ordner `eda/output/`.\n\n## Quellen\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "data_report_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}